canvas_sources:
  - name: "Harvard Canvas"
    url: "https://canvas.harvard.edu/feeds/calendars/user_OtFYRvlM3UBCrdIXqkntOJerw5Jibi5UZ5IGhyYV.ics"
  - name: "Harvard Business School Canvas"
    url: "https://hbs.instructure.com/feeds/calendars/user_03CKmwa1f7Twza2acVYcZZuGYDB30tIj3eiOvTk1.ics"
  - name: "MIT Canvas"
    url: "https://canvas.mit.edu/feeds/calendars/user_Pt8P7SgOM54JioJ1QXYhjylaq9Jx33VJvUZwx8iA.ics"

ics_sources:
  - name: "Outlook"
    url: "https://outlook.office365.com/owa/calendar/e23d148f6fd44ad4bc687da2d033d868@gse.harvard.edu/eba8bfccb9d9480897360f7cac9758e210122385807434738636/calendar.ics"

gmail:
  search_query: "has:attachment (filename:ics OR filename:ical) OR subject:(ticket OR reservation OR rsvp OR itinerary OR booking) newer_than:120d"

selfcare:
  preferred_windows:
    - day: "Mon-Fri"
      start: "07:00"
      end: "10:30"
      min_minutes: 60
    - day: "Mon-Fri"
      start: "16:30"
      end: "20:30"
      min_minutes: 60
  target_minutes: [120, 60]
  buffers_minutes: 10
  max_per_day: 1

home:
  address: "Cambridge, MA"

academic_calendar:
  term_name: "Fall 2025"
  term_start_date: "2025-09-01"
  term_end_date: "2025-12-15"
  holidays:
    - name: "Thanksgiving Break"
      start: "2025-11-25"
      end: "2025-11-29"
    - name: "Winter Break"
      start: "2025-12-24"
      end: "2026-01-01"
